/**
 * Expo config plugin for Ghost native module integration.
 *
 * This plugin handles both Android and iOS:
 *
 * Android:
 *   - Copies native-src/android/*.kt to android/app/src/main/java/com/ghost/testbed/
 *   - Copies ghost.aar from ghost-go/build/ to android/app/libs/
 *   - Configures build.gradle for AAR dependency
 *   - Registers GhostPackage in MainApplication
 *
 * iOS:
 *   - Copies native-src/ios/*.{swift,m,h} to ios/GhostTestbed/
 *   - Copies Ghost.xcframework from ghost-go/build/ to ios/
 *   - Configures Podfile for framework dependency
 *
 * Native source files are stored in native-src/ (committed to git).
 * The android/ and ios/ directories are generated by expo prebuild.
 */

const {
  withAppBuildGradle,
  withMainApplication,
  withDangerousMod,
  withXcodeProject,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// =============================================================================
// Utility Functions
// =============================================================================

function copyFileIfExists(src, dest, description) {
  if (fs.existsSync(src)) {
    const destDir = path.dirname(dest);
    if (!fs.existsSync(destDir)) {
      fs.mkdirSync(destDir, { recursive: true });
    }
    fs.copyFileSync(src, dest);
    console.log(`[withGhostModule] Copied ${description}`);
    return true;
  }
  return false;
}

function copyDirContents(srcDir, destDir, extension, description) {
  if (!fs.existsSync(srcDir)) {
    console.warn(`[withGhostModule] Source directory not found: ${srcDir}`);
    return 0;
  }

  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }

  const files = fs.readdirSync(srcDir).filter(f => f.endsWith(extension));
  for (const file of files) {
    fs.copyFileSync(path.join(srcDir, file), path.join(destDir, file));
  }

  if (files.length > 0) {
    console.log(`[withGhostModule] Copied ${files.length} ${description} file(s)`);
  }
  return files.length;
}

// =============================================================================
// Android Plugin Functions
// =============================================================================

function withGhostAndroidNativeFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const srcDir = path.join(projectRoot, 'native-src', 'android');
      const destDir = path.join(
        projectRoot, 'android', 'app', 'src', 'main', 'java', 'com', 'ghost', 'testbed'
      );

      // Copy all Kotlin files
      copyDirContents(srcDir, destDir, '.kt', 'Android Kotlin');

      return config;
    },
  ]);
}

function withGhostAarCopy(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const libsDir = path.join(projectRoot, 'android', 'app', 'libs');
      const sourceAar = path.join(projectRoot, '..', 'ghost-go', 'build', 'ghost.aar');
      const destAar = path.join(libsDir, 'ghost.aar');

      if (!fs.existsSync(libsDir)) {
        fs.mkdirSync(libsDir, { recursive: true });
      }

      if (!copyFileIfExists(sourceAar, destAar, 'ghost.aar')) {
        console.warn('[withGhostModule] WARNING: ghost.aar not found at', sourceAar);
        console.warn('[withGhostModule] Run "make android" in ghost-go/ to build it');
      }

      return config;
    },
  ]);
}

function withGhostBuildGradle(config) {
  return withAppBuildGradle(config, (config) => {
    let gradle = config.modResults.contents;

    // Add flatDir repository for local AAR files
    if (!gradle.includes('flatDir')) {
      gradle = gradle.replace(
        /android\s*\{/,
        `android {
    repositories {
        flatDir { dirs 'libs' }
    }`
      );
      console.log('[withGhostModule] Added flatDir repository');
    }

    // Add ghost.aar dependency
    if (!gradle.includes("name: 'ghost'")) {
      gradle = gradle.replace(
        /dependencies\s*\{/,
        `dependencies {
    implementation(name: 'ghost', ext: 'aar')`
      );
      console.log('[withGhostModule] Added ghost.aar dependency');
    }

    config.modResults.contents = gradle;
    return config;
  });
}

function withGhostMainApplication(config) {
  return withMainApplication(config, (config) => {
    let mainApp = config.modResults.contents;

    // Add import for GhostPackage
    if (!mainApp.includes('com.ghost.testbed.GhostPackage')) {
      mainApp = mainApp.replace(
        /^(import\s+)/m,
        'import com.ghost.testbed.GhostPackage\n$1'
      );
      console.log('[withGhostModule] Added GhostPackage import');
    }

    // Add GhostPackage to the packages list
    if (!mainApp.includes('GhostPackage()')) {
      // Try pattern for newer Expo templates with packages.apply
      if (mainApp.includes('packages.apply')) {
        mainApp = mainApp.replace(
          /(packages\.apply\s*\{)/,
          '$1\n                add(GhostPackage())'
        );
        console.log('[withGhostModule] Added GhostPackage via packages.apply');
      }
      // Try pattern for PackageList().packages
      else if (mainApp.includes('PackageList(this).packages')) {
        mainApp = mainApp.replace(
          /PackageList\(this\)\.packages/,
          'PackageList(this).packages.apply { add(GhostPackage()) }'
        );
        console.log('[withGhostModule] Added GhostPackage via apply block');
      }
    }

    config.modResults.contents = mainApp;
    return config;
  });
}

// =============================================================================
// iOS Plugin Functions
// =============================================================================

function withGhostIOSNativeFiles(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const srcDir = path.join(projectRoot, 'native-src', 'ios');
      const appName = config.modRequest.projectName || 'GhostTestbed';
      const destDir = path.join(projectRoot, 'ios', appName);

      if (!fs.existsSync(destDir)) {
        fs.mkdirSync(destDir, { recursive: true });
      }

      // Copy Swift, ObjC, and header files
      const extensions = ['.swift', '.m', '.h'];
      let totalCopied = 0;

      for (const ext of extensions) {
        totalCopied += copyDirContents(srcDir, destDir, ext, `iOS ${ext}`);
      }

      if (totalCopied === 0) {
        console.warn('[withGhostModule] No iOS native files found in', srcDir);
      }

      return config;
    },
  ]);
}

function withGhostXcframeworkCopy(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const sourceFramework = path.join(projectRoot, '..', 'ghost-go', 'build', 'Ghost.xcframework');
      const destFramework = path.join(projectRoot, 'ios', 'Ghost.xcframework');

      // xcframework is a directory, use recursive copy
      if (fs.existsSync(sourceFramework)) {
        fs.cpSync(sourceFramework, destFramework, { recursive: true });
        console.log('[withGhostModule] Copied Ghost.xcframework');
      } else {
        console.warn('[withGhostModule] WARNING: Ghost.xcframework not found at', sourceFramework);
        console.warn('[withGhostModule] Run "make ios" in ghost-go/ to build it');
      }

      return config;
    },
  ]);
}

function withGhostXcodeProject(config) {
  return withXcodeProject(config, (config) => {
    // Note: Programmatically adding xcframeworks to Xcode projects is complex.
    // The framework is copied to ios/, but manual Xcode setup may be needed.
    // TODO: Implement proper xcframework linking when we have iOS builds working.
    console.log('[withGhostModule] iOS: Ghost.xcframework copied to ios/');
    console.log('[withGhostModule] iOS: Manual Xcode setup may be required:');
    console.log('[withGhostModule]   1. Open ios/*.xcworkspace in Xcode');
    console.log('[withGhostModule]   2. Add Ghost.xcframework to "Frameworks, Libraries, and Embedded Content"');

    return config;
  });
}

// =============================================================================
// Main Plugin Export
// =============================================================================

module.exports = function withGhostModule(config) {
  // Android configuration
  config = withGhostAndroidNativeFiles(config);  // Copy Kotlin files from native-src/
  config = withGhostAarCopy(config);             // Copy ghost.aar from ghost-go/build/
  config = withGhostBuildGradle(config);         // Configure build.gradle for AAR
  config = withGhostMainApplication(config);     // Register GhostPackage

  // iOS configuration
  config = withGhostIOSNativeFiles(config);      // Copy Swift/ObjC from native-src/
  config = withGhostXcframeworkCopy(config);     // Copy Ghost.xcframework from ghost-go/build/
  config = withGhostXcodeProject(config);        // Log setup instructions

  return config;
};
